import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillInstagram,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Html from '../public/html.png';
import Css from '../public/css.png';
import Javascript from '../public/javascript.png';
import Tailwind from '../public/tailwind.png';
import Github from '../public/github1.png';
import NextJS from '../public/nextjs.png';
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "" : "dark"}>
      <Head>
        <title>Harsha.Pi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-teal px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Harsha. Pi</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Harshavardhan Hajeri
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Student at BITS GOA.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Hello there! I am interested in Quantum Computing
              and Web-Development. let's start Building!
            </p>
            <div className="text-4xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
             <a href="www.instagram.com/harsha.pi">
              <AiFillInstagram />
              </a>
            </div>
            
          </div>
        
          
          
         <div>
            <h2 className="text-4xl mb-4 py-1 dark:text-white text-center ">Skills</h2>
            
          </div>
        <div className="max-w-[1240px] mx-auto flex flex-col justify-center h-full pb-8 "> 
         <div className='grid grid-cols-2 lg:grid-cols-3 gap-8 py-4 '>
          <div className='p-4 shadow-xl rounded-xl hover:scale-105 ease-in duration-300    dark:bg-slate-100'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className='m-auto'>
                <Image src={Html} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center '>
                <h3>HTML</h3>
              </div>
            </div>
          </div>
          <div className='p-4 shadow-xl rounded-xl hover:scale-105 ease-in duration-300     dark:bg-slate-100'>
            <div className='grid grid-cols-2 gap-4 justify-center  items-center'>
              <div className='m-auto'>
                <Image src={Css} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center '>
                <h3>CSS</h3>
              </div>
            </div>
          </div>
          <div className='p-4 shadow-xl rounded-xl hover:scale-105 ease-in duration-300    dark:bg-slate-100 '>
            <div className='grid grid-cols-2 gap-4 justify-center  items-center'>
              <div className='m-auto'>
                <Image src={Javascript} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center '>
                <h3>JavaScript</h3>
              </div>
            </div>
          </div>
          
          <div className='p-4 shadow-xl rounded-xl hover:scale-105 ease-in duration-300   dark:bg-slate-100'>
            <div className='grid grid-cols-2 gap-4 justify-center  items-center'>
              <div className='m-auto'>
                <Image src={Tailwind} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center '>
                <h3>Tailwind</h3>
              </div>
            </div>
          </div>
         
          <div className='p-4 shadow-xl rounded-xl hover:scale-105 ease-in duration-300    dark:bg-slate-100'>
            <div className='grid grid-cols-2 gap-4 justify-center  items-center'>
              <div className='m-auto'>
                <Image src={Github} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center '>
                <h3>Github</h3>
              </div>
            </div>
          </div>
          <div className='p-4 shadow-xl rounded-xl hover:scale-105 ease-in duration-300    dark:bg-slate-100'>
            <div className='grid grid-cols-2 gap-4 justify-center  items-center'>
              <div className='m-auto'>
                <Image src={NextJS} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center '>
                <h3>Next</h3>
              </div>
            </div>
          </div>
        </div>
        </div></section>
       
      </main>
    </div>
  );
}
